version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/src/sohome_client"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/src/sohome_client"
    schedule:
      interval: "daily"
